# Generated by Django 3.2 on 2021-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
